### ISSUE TITLE
integration/docker: quota and period are too small

### ISSUE THREAD

**Issue by devimc** [kata-containers/tests#1152]
Current values to test quota and period are too small for a hypervisor, since we are about to support cpu cgroups in the host those values should be at least > 10000

**Comment by grahamwhaley** [comment]
... why? just ooi, got a reference?

**Comment by devimc** [comment]
the experience is a good reference :smile:  run next commands and you'll see what I'm talking about

````
docker run --name foo -dti --runtime kata-runtime debian bash
sudo mkdir -p /sys/fs/cgroup/cpu,cpuacct/kata-tmp/
echo $(pgrep qemu) | sudo tee /sys/fs/cgroup/cpu,cpuacct/kata-tmp/cgroup.procs 
echo 2000 | sudo tee /sys/fs/cgroup/cpu,cpuacct/kata-tmp/cpu.cfs_quota_us 
docker exec -ti foo bash
# ls
````

**Comment by grahamwhaley** [comment]
but, not posting details here does not help anybody understand the why, or help anybody in the future with the same/similar issue search for an answer....
You have it on your screen, you seem to understand what the issue is and why it comes about ... g'on, elucidate it into this Issue so we can all not have to type it in and work it out for ourselves..... dare you ....
