### ISSUE TITLE
Clearcontainers build fails in setup on Fedora

### ISSUE THREAD

**Issue by jberkus** [kata-containers/tests#119]
This issue resolved via Slack.

**Comment by grahamwhaley** [comment]
Might have been good to update the Issue here so we had some sort of searchable record for others to find in the future :-) I'll add some notes:
From your original message, you had:

```
12:00 $ ./setup.sh 
Set up environment
github.com/clearcontainers/runtime (download)
ERROR: cannot find /src/github.com/clearcontainers/runtime/versions.txt
```

I suspect you did not have a `GOPATH` setup (which would normally appear on the front of the `/src/github....` - can you confirm.

We should probably make the CI scripts check for a GOPATH being set, and abort if not as we are relying upon it (/cc @chavafg )
