### ISSUE TITLE
metrics: Failing CI for stable-1.5

### ISSUE THREAD

**Issue by sboeuf** [kata-containers/tests#1232]
The metrics CI fails quickly on every PR submitted to the stable-1.5 branch since it looks for an OBS path that doesn't exist anymore.
Here is the fix that has been merged for the regular CI: https://github.com/kata-containers/tests/pull/1229

/cc @grahamwhaley @chavafg

**Comment by grahamwhaley** [comment]
It might be because we are also missing #1225 , which means a stable branch run may then have 'infected' the bare metal machines package configs...
Let me check what is on the slave right now, and then I'll see if I can raise a PR to fix #1225 

/cc @nitkon @tuan-hoang1 as if this is right then it may also affect Power8 and S390 slaves as well.

**Comment by grahamwhaley** [comment]
Yep, that is what I think has happened - the apt file has `release` in it instead of `releases`. I cleared that out at the end of last week, so it has re-appeared since then.

```bash
# pwd
/etc/apt/sources.list.d
root@kata-metric1:/etc/apt/sources.list.d# cat kata-containers.list
deb http://download.opensuse.org/repositories/home:/katacontainers:/release/xUbuntu_16.04/ /
```

**Comment by GabyCT** [comment]
Closing this issue as we are not supporting this release
