### ISSUE TITLE
Some baremetal logs are getting pretty big

### ISSUE THREAD

**Issue by chavafg** [kata-containers/tests#1265]
I found on the jenkins master that some jobs are getting pretty big logs, e.g.
```
jenkins@jenkins:~/jobs/kata-containers-shim-Power8-ubuntu-16-04-PR-initrd/builds$ du -hs *
20K	1
113M	2
1.4G	3
1.4G	4
1.4G	5
 ```

When running the `teardown.sh`, we collect the journals of several services and kata components, but these do not get deleted after each CI run and now they seem to be growing too much that could lead to having space issues on our Jenkins master.

I think that a simple solution would be to add something like this on the baremetal cleanups:
```
sudo rm -rf /run/log/journal/ && sudo systemctl restart systemd-journald
```

@grahamwhaley @Pennyzct @nitkon @alicefr 
wdyt?

**Comment by grahamwhaley** [comment]
Ah, so we collect **all** of the log. The other option maybe is to use a `--since` to only grab the portion of the logs relevant to the current build.... if we can find a nice way to find the 'start time' of the build that is.

Also, sure, cleaning up the kata specific logs on the baremetal slaves is not a bad idea either. I think maybe on the metrics CI slave we are OK as we try to reboot between each build - but we can still make this a generic cleanup (it won't do any harm on the metrics slaves for instance).

**Comment by nitkon** [comment]
@chavafg : As @grahamwhaley said, can we not delete the journalctl logs from the bare metal Jenkins Slave node and instead store only the logs relevant for that CI as artefacts on the Jenkins master node, thus saving space on the master.

**Comment by chavafg** [comment]
Agree, grabbing the relevant logs using `--since` should be enough.
