### ISSUE TITLE
Set kata-runtime as default-runtime can cause container image build issues

### ISSUE THREAD

**Issue by alicefr** [kata-containers/tests#1266]
Hi,

I recently had the problem that with the script in tests `kata-runtime` was set as `default-runtime` (see https://github.com/kata-containers/tests/blob/3c0225185a07853ddfa2293c5abb6ae79fe1eafb/cmd/container-manager/manage_ctr_mgr.sh#L298). The issue arises when we try to build a docker image and runtime=kata-runtime. In this case, kata is used to build docker images as for example for `virsh/stress`. It could be safer to explicitly set default-runtime to `runc`.
Wdyt?

**Comment by jodh-intel** [comment]
Yes, this is a known issue and a limitation of docker (which doesn't provide a way to specify the runtime for `docker build`). See:

- https://github.com/kata-containers/osbuilder/blob/master/image-builder/image_builder.sh#L105..L110
- https://github.com/kata-containers/osbuilder/blob/master/tests/test_images.sh#L31..L32
- https://github.com/kata-containers/osbuilder/blob/master/rootfs-builder/rootfs.sh#L322

**Comment by grahamwhaley** [comment]
Yep, known issue, and annoying that docker don't let you choose the runtime for a build :-( (yeah, about twice a year I consider if we should go PR a change into docker... ;-) ).
@alicefr - are you still seeing this as a problem in the CI system? I thought you had it failing in the S390 CI, whereas it was working for the x86 arch CI.

I do suspect we could flip the CI/test scripts to make kata not the default, as afaik we always set `RUNTIME=kata-runtime` when running the CIs, and all the scripts pick up and use that.

/cc @egernst @chavafg for thoughts.

**Comment by alicefr** [comment]
I'm trying to set an internal jenkins for s390 and I'm having this issue in building the image `virsh/stress`

**Comment by egernst** [comment]
@grahamehaley I think changing default makes sense. 

Exploring making image builders work / and identifying the gap would be interesting, too.

**Comment by alicefr** [comment]
The point is that in the docker testsuite, other archs rather then x86 build the virsh/stress image. Calling
```sh
$ .ci/jenkins_job_build.sh "github.com/kata-containers/runtime"
```
kata is installed as default-runtime. I have a private branch where I set `--default-runtime=runc` and it worked. Either I'm doing that for s390x only or I can set for all. Probably, it could avoid future issues. Wdyt?

**Comment by jodh-intel** [comment]
@chavafg - have you got any thoughts on this (including how difficult / time consuming it would be to switch the default runtime back to `runc` and always call `--runtime kata-runtime` for all docker tests)?

We do document setting the Kata runtime as the default in all the [install guides](https://github.com/kata-containers/documentation/tree/master/install) for user convenience. However, that shouldn't need to change since although the doc repo uses this one, it only uses the static checker atm.

**Comment by chavafg** [comment]
I think it would be pretty easy. I took a quick look and seems like we are already using `--runtime kata-runtime` on all docker calls. So we just need to remove the part where we configure it as the default. Will open a PR and see if everything goes smooth.

**Comment by jodh-intel** [comment]
Thanks @chavafg !

**Comment by grahamwhaley** [comment]
:idea: - try setting the default docker runtime to something that fails (like `/bin/false`), and then run the CI and see what happens - that way you will find out if anything is trying to use the default runtime - as otherwise we might end up with some parts of the CI actually running runc, and silently passing ;-)

**Comment by jodh-intel** [comment]
Cute hack @grahamwhaley! I'd tweak that slightly and suggest wrapping the false call in a script that squirts an error to stderr, maybe throw in a `ps` to see system state at time of erroneous call, then dies.

**Comment by chavafg** [comment]
So I ran the tests locally using a false runtime `/usr/local/bin/noruntime` and found 2 tests that fails because using default runtime is `build with docker`. 
```
Stderr: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/072a30838f3cfdde6d85dccea9da402afbd5520b6e4802be82f69c651da30656/lo
g.json: no such file or directory): fork/exec /usr/local/bin/noruntime: no such file or directory: unknown      
```
Anyway I think this is ok knowing that docker build using kata will fail. 


The other test is swarm.
Seems like there is no way to specify a runtime when running `docker service create`. At least from the docker service command line reference. https://docs.docker.com/engine/reference/commandline/service_create/ 
But, do we still care about swarm? 

Other places where the runtime is not specified are:

- https://github.com/kata-containers/tests/blob/master/metrics/report/makereport.sh#L50 
In this case I think it is ok, as this container is created for creating a report. 

- https://github.com/kata-containers/tests/blob/master/metrics/network/network-metrics-nginx-ab-benchmark.sh#L75 
I this case, we should specify the runtime.

**Comment by jodh-intel** [comment]
Thanks @chavafg!

@grahamwhaley and @GabyCT  - I've raised #1286 and #1287 if you could look at fixing those scripts?

**Comment by alicefr** [comment]
Any updates/ideas on this issue?

**Comment by grahamwhaley** [comment]
@alicefr - thanks for nudging :-)
Looks like the two raised issues were fixed, and having re-read the thread I now understand what the issue is for non-x86 CIs. There were no disagreements here, so I think we are agreed we are good to change the default runtime to not-kata....
Is there a PR to do this? I didn't see one - if not, would you like to raise one @alicefr ?

**Comment by alicefr** [comment]
@grahamwhaley thanks for the quick reply! You're right I didn't raise any PR because I was not sure about your opinion. I'd like to explicitly set the default-runtime to runc, is that fine?

**Comment by grahamwhaley** [comment]
I'm not sure if we need to explicitly set it, or if we can just not set it at all and let it default (which, you'd think for a default docker install, would always default to runc).
I'm fairly happy either way, particularly for the CI systems. Any preference @chavafg ?

**Comment by alicefr** [comment]
@grahamwhaley thx for the suggestion! I personally prefer to use the default runtime from docker and not explicitly set it as you suggest.

**Comment by chavafg** [comment]
I think we can move to use runc as default, but swarm will be using runc when tested. Although for the moment we don't really care about swarm, we can remove swarm testing? or configure kata as default when testing swarm and get back to runc when we finish testing it? ... @jodh-intel @grahamwhaley  @egernst, wdyt?

**Comment by jodh-intel** [comment]
@mcastelino - wdyt? Shall we just remove the swarm tests?

Swarm is [still tied to docker `1.12.1`](https://github.com/kata-containers/runtime/blob/master/versions.yaml#L210) which was released [almost three years ago](
https://github.com/moby/moby/releases/tag/v1.12.1). Would anyone really be using a version of docker this old just for swarm?

**Comment by alicefr** [comment]
If you don't want to remove the swarm testcases, something like this https://github.com/kata-containers/tests/pull/1382 ?

**Comment by chavafg** [comment]
I am taking a look at the swarm tests and I don't see where we switch to docker 1.12.1... It seems that we are testing with 18.06... /cc @GabyCT 

@alicefr I think that would help, but we would still need to call the `"./manage_ctr_mgr.sh" docker configure -r kata-runtime` before running the [swarm tests](https://github.com/kata-containers/tests/blob/master/integration/swarm/swarm.bats). and restore the configuration after we run the tests.

**Comment by GabyCT** [comment]
@chavafg we have a basic swarm test which currently is working with 18.06, more complex swarm tests like pinging replicas, etc have not been added in the test repository as they are not working so right now we do not have anything that uses 1.12.1

**Comment by ravvy00** [comment]
Same issue whenever setting kata-runtime as default runtime for dockerd K8s cluster is not working, do we have a solution for that also.

cat <<EOF | sudo tee /etc/systemd/system/docker.service.d/kata-containers.conf
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd -D --add-runtime kata-runtime=/usr/bin/kata-runtime --default-runtime=kata-runtime
EOF

**Comment by chavafg** [comment]
@ravvy00 for k8s, kata only works using containerd or cri-o.
