### ISSUE TITLE
Add test to check dmesg errors

### ISSUE THREAD

**Issue by devimc** [kata-containers/tests#1274]
Add test to check whether dmesg logs errors, for example next test MUST fail

```
docker run -ti --runtime=kata-runtime debian dmesg -l err
[    0.293030] EXT4-fs (pmem0p1): DAX unsupported by block device. Turning off DAX.
```

**Comment by grahamwhaley** [comment]
hmm... so, at the point we add a 2nd string to search for, I'm going to suggest we add a file (yaml??) that lists all the things we should *not* see. And maybe all the things we *should* see as well... heh

**Comment by sboeuf** [comment]
@devimc that's a very good idea to introduce some testing to validate we're not losing DAX support everytime we do a release.

Now, I'm wondering if checking specific strings is good enough, since we never know if those comments could evolve with future kernel releases.

**Comment by jodh-intel** [comment]
> we never know if those comments could evolve with future kernel releases.

+1 for the concept but I agree: I don't think we can rely on dmesg output (I have an inkling we've been bitten by the format changing before... wasn't it detecting the "end of boot" @grahamwhaley?)

However, how about we introduce some sort of test API so that a shell script can call:

```sh
ensure_kernel_feature "dax"
ensure_kernel_feature "bacon"
```

... and that will magically dtrt in `lib.sh` or whatever. In the first instance we could just parse dmesg until we find a better way (probing somehow?)

**Comment by grahamwhaley** [comment]
it was, we did.
I think whatever we do it may rot at some point - I suspect that is unavoidable. I'd be happy to go with the 'this is better than the nothing we have now' approach, and pay the costs later :-)
