### ISSUE TITLE
CI: Run CI against tests repo on IBM Power Machine

### ISSUE THREAD

**Issue by nitkon** [kata-containers/tests#1644]
Clone the Jenkins job to run CI tests against test repo on Power 8 Server. 
cc @grahamwhaley @chavafg

**Comment by grahamwhaley** [comment]
@nitkon has asked if we can enable Power CI on the tests repo now as well.
@nitkon - looking at the recent history, although it is 'pretty red', I see recent fails are probably justified due to:
- non-working PRs, like the qemu4 and CI pre-build binaries PRs
- lots of backport build fails?

Now, I suspect those backports are to stable branches, and maybe you don't support stable backport CI at present on Power? If so, let's try and configure the white/blacklist branches on the github jenkins plugin to exclude those from Power builds *before* we clone. wdyt?

**Comment by grahamwhaley** [comment]
Chatted to @nitkon - had a look at some of the fails. Although they are valid fails as we have some 'WIP' PRs in flight, we came to realise we should probably not run the CIs against stable branches for Power yet, as the fixes that went in to make the CI stable on Power are probably not on those branches.

@nitkon - therefore, what you first should do is go to the Power runtime PR tracking job on the Jenkins master, find the 'github pull request builder' dialog box, locate where it has the 'black/whitelists' of which branches to track in the upstream repo, and put `master` in the whitelist. That should make it then **only** track the master PRs.
Once that is done, and we see it working, then I think you will be ready to do a clone of that job to make a PR tracking job for the tests repo.

Whilst you are there, if you have not already, I would recommend reading all dialogs and entries on the Jenkins job (and definitely press any 'advanced' expansion buttons, as we do have stuff buried in there as well), and check you understand what each bit is doing ;-)

**Comment by GabyCT** [comment]
Closing this issue as the CI on Power 8 has been enabled
