### ISSUE TITLE
Upgrade to yq 3.1.0

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/tests#2290]
The anchor bug (https://github.com/kata-containers/tests/pull/2275) is fixed in yq 3.1.0 by specifying the new "`-X` / `-explodeAnchors` option as specified in https://mikefarah.gitbook.io/yq/commands/read#exploding-anchors.

Related: https://github.com/mikefarah/yq/issues/340

**Comment by grahamwhaley** [comment]
OK, let's clarify....
I see that we have `yq` install scripts in both the [tests repo](https://github.com/kata-containers/tests/commit/94c25fc0274f62630eb63ed2b3c2e0a64c6473b7#diff-90ebfaad0f4f9e62700603c97466a36b), and the [runtime repo](https://github.com/kata-containers/runtime/commit/7fa03902b428eab18296294dde3bb966ad9d0be8)...
and the runtime one already pinned `yq` to version 2.3.0, since March 2019...

If feels like we have two options:
1) Update both the tests and runtime repos to use the latest (un-pinned?) version of `yq`, *and* add the `-X` to all relevant calls to `yq` (which I think are isolated in the get_version function that parses the `versions.yaml` files, I hope).
1) Leave it as-is. v2.3.0 of `yq` has been working for us for ever, it does what we need, so we could just leave it alone for now?

/cc @jodh-intel @chavafg @amshinde and just fyi @Pennyzct

**Comment by chavafg** [comment]
@grahamwhaley I think we should stick to option 1 as @Pennyzct found an issue with `yq` 3.2.0. See https://github.com/kata-containers/tests/pull/2294#issuecomment-583969423. 
But should we stick to 3.1? 
Or remove the version and always get the latest? This one may break us in the future...

**Comment by Pennyzct** [comment]
Hi~ @chavafg @grahamwhaley 
the 2.3.0 version yq has already caused errors in ARM CI, So I'm with option 1. ;).
And maybe we should go back to always using the latest one??
