### ISSUE TITLE
ci: do not require all markdown files to be referenced

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/tests#2474]
# Description of problem

There are many markdown files that are not referenced by each other but CI `check-markdown` would require each of them to be referenced. For document repo, it is a fair requirement but for code repos, it is common to have unreferenced markdown files.

For example, the runtime repo has a few generated markdown files that are unsuitable to reference.
```
./virtcontainers/pkg/cloud-hypervisor/client/docs/PmemConfig.md
./virtcontainers/pkg/cloud-hypervisor/client/docs/VmConfig.md
./virtcontainers/pkg/cloud-hypervisor/client/docs/NetConfig.md
./virtcontainers/pkg/cloud-hypervisor/client/docs/FsConfig.md
./virtcontainers/pkg/cloud-hypervisor/client/docs/DeviceConfig.md
./virtcontainers/pkg/cloud-hypervisor/client/docs/ConsoleConfig.md
./virtcontainers/pkg/cloud-hypervisor/client/docs/VmRemoveDevice.md
./virtcontainers/pkg/cloud-hypervisor/client/docs/VmResize.md
./virtcontainers/pkg/cloud-hypervisor/client/docs/VsockConfig.md
./virtcontainers/pkg/cloud-hypervisor/client/docs/VmAddDevice.md
./virtcontainers/pkg/cloud-hypervisor/client/docs/InitramfsConfig.md
./virtcontainers/pkg/cloud-hypervisor/client/docs/MemoryConfig.md
./virtcontainers/pkg/cloud-hypervisor/client/docs/CpusConfig.md
./virtcontainers/pkg/cloud-hypervisor/client/docs/VmmPingResponse.md
./virtcontainers/pkg/cloud-hypervisor/client/docs/RestoreConfig.md
./virtcontainers/pkg/cloud-hypervisor/client/docs/VmInfo.md
./virtcontainers/pkg/cloud-hypervisor/client/docs/KernelConfig.md
./virtcontainers/pkg/cloud-hypervisor/client/docs/RngConfig.md
./virtcontainers/pkg/cloud-hypervisor/client/docs/DefaultApi.md
./virtcontainers/pkg/cloud-hypervisor/client/docs/CmdLineConfig.md
./virtcontainers/pkg/cloud-hypervisor/client/docs/DiskConfig.md
./virtcontainers/pkg/cloud-hypervisor/client/docs/VmSnapshotConfig.md
./virtcontainers/pkg/cloud-hypervisor/client/README.md
```

Most markdown files under virtcontainers package are not referenced either. It seems that the `check-markdown` static test would fail for runtime repo anytime a markdown file is updated.

This was discovered in https://github.com/kata-containers/kata-containers/pull/193 where the markdown checker is triggered and complaining that `src/agent/README.md` is not referenced.

**Comment by grahamwhaley** [comment]
I have a suspicion that we might have filtered out some 'special cases', such as `pkg` or `virtcontainers` from the check, like we do for `vendor`. I'd much rather we filtered out known cases/issues, and still have the check in place for the general case of the codebase. Having un-referenced documents around has caused us problems in the past where people just cannot find a file (doc) they are looking for by browsing through the markdown.
I'll defer to @jodh-intel for thoughts...

**Comment by bergwolf** [comment]
In that case, is kata-containers repository `src/agent` filtered? Can we filter `src/runtime` as well? Or possibly we should just filter `src/` altogether there.

`tests/cmd/check-markdown/README.md` doesn't mention any of the reference requirement nor how to filter out though.

**Comment by jodh-intel** [comment]
Hi @bergwolf - the static checker already excludes the files you're talking about. The code is slightly convoluted, but the key line is here:

- https://github.com/kata-containers/tests/blob/master/.ci/static-checks.sh#L55

Clearly, we want to check all the files that *we* have control over, so we special-case those sets of files (like the clh docs) that we don't.

I'm not clear why you are talking about filtering below `src/` - the new agent is there, but there is only a single `README.md` there. And that file passes the markdown checkers checks:

```sh
$ ../tests/cmd/check-markdown/kata-check-markdown -s check src/agent/README.md &>/dev/null && echo ok
ok
```

Finally, `tests/cmd/check-markdown/README.md` doesn't mention filtering because that tool only checks a single file - the logic to determine which files to pass to the markdown checker is in the static checks script:

- https://github.com/kata-containers/tests/blob/master/.ci/static-checks.sh#L618..L620

**Comment by bergwolf** [comment]
Fair enough. Let's drop this.
