### ISSUE TITLE
ci: Allow to overwrite the repositories on install scripts

### ISSUE THREAD

**Issue by wainersm** [kata-containers/tests#2535]
The `resolve-kata-dependencies.sh` allows to overwrite the kata-containers repositories, and it results in cloning them from arbitrary locations. This is a nice feature that helps a lot when you working on your forked repositories.

However, most of the other scripts does not allow that because they have hard-coded in values. As for example, `install_proxy.sh` is always to clone and build from `github.com/kata-containers/proxy`.

This is a RFE to allow cloning and building the components from arbitrary locations too.

**Comment by wainersm** [comment]
BTW, I need this enhancement in order to work on #2527

**Comment by grahamwhaley** [comment]
ack, having the feature would be nice maybe. Also the ability to specify a branch to use for all the repos would be nice (I don't think we have that at present do we @jcvenegas @chavafg ?). That was an item I ran into in the past and did a preliminary PR that didn't land iirc.
Be aware, some of the repos (like the runtime), will only build if they are checked out at their root go path (that is, the main repo) - because, Go is like that - it has references to the repo path in the code, and if the code is not at that path, it bawks. iirc, it fails to build in the virtcontainers subdir in odd and hard to work out ways. I know this as normally I work in my own user branch and push PRs from there, but I can't do that for the runtime, as it won't build/test in my user branch/checkout on my disk ;-)

**Comment by wainersm** [comment]
> ack, having the feature would be nice maybe. Also the ability to specify a branch to use for all the repos would be nice (I don't think we have that at present do we @jcvenegas @chavafg ?). That was an item I ran into in the past and did a preliminary PR that didn't land iirc.

Indeed, specify a branch would be beautiful!
 
> Be aware, some of the repos (like the runtime), will only build if they are checked out at their root go path (that is, the main repo) - because, Go is like that - it has references to the repo path in the code, and if the code is not at that path, it bawks. iirc, it fails to build in the virtcontainers subdir in odd and hard to work out ways. I know this as normally I work in my own user branch and push PRs from there, but I can't do that for the runtime, as it won't build/test in my user branch/checkout on my disk ;-)

I just hit that issue on building runtime, thanks for letting my aware of this @grahamwhaley :
```
create.go:16:2: cannot find package "github.com/kata-containers/runtime/virtcontainers" in any of:
	/go/src/github.com/wainersm/kc-runtime/vendor/github.com/kata-containers/runtime/virtcontainers (vendor tree)
	/usr/local/go/src/github.com/kata-containers/runtime/virtcontainers (from $GOROOT)
	/go/src/github.com/kata-containers/runtime/virtcontainers (from $GOPATH)
```

**Comment by grahamwhaley** [comment]
@wainersm - I dug out my old PR for 'versioned builds', just for references to the idea: https://github.com/kata-containers/tests/pull/865

**Comment by wainersm** [comment]
@grahamwhaley At the moment I won't be able to work on a more sophisticated solution. So perhaps we could merge this PR (if all reviewers ack) and assume the developer knows how to trick its forked repos to get Go binaries built? What do you think?

**Comment by grahamwhaley** [comment]
Sure @wainersm, this is a useful PR as is I think. Looks like you have enough acks on the PR already - just need to have folks check why those CIs are failing.
