### ISSUE TITLE
Log parser fails to parse log entries containing escaped backslashes

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/tests#2570]
The [log parser](https://github.com/kata-containers/tests/tree/master/cmd/log-parser) cannot seemingly parse lines containing a double-backslash like this:

```
time="2020-05-19T15:23:53.073955287-07:00" level=info msg="[    0.307393] systemd[1]: unit_file_build_name_map: normal unit file: /usr/lib/systemd/system/system-systemd\\x2dcryptsetup.slice\n" name=kata-proxy pid=42100 sandbox=290c4fa90c7350d89d1b2fdf507bfc86cf5a0c5e309dcdf8e12361daa5213aae source=agent
```

The problem being:

```
/usr/lib/systemd/system/system-systemd\\x2dcryptsetup.slice
                                      ~~
```

Reported here: https://github.com/kata-containers/runtime/issues/2692#issuecomment-632380999

**Comment by jodh-intel** [comment]
@cmaf - this might be an interesting bug for you to look at?

**Comment by cmaf** [comment]
@jodh-intel I was able to replicate (including the string the log generated) with kata 1.11.0 (with additional errors), logfmt 0.3.0 and 0.5.0, and kata 1.11.1 with logfmt 0.5.0. The parsing error still occurs with kata-runtime commit ea74c96dc4cf & logfmt 0.5.0 but I can't get the logs to generate the same string with this version so I had to manually add it. 

Failing on `\\x` seems to be expected behavior from logfmt and I haven't understood yet if/how it is a bug. Is the string `/usr/lib/systemd/system/system-systemd\\x2dcryptsetup.slice` that is generated by the logs malformed somehow? There aren't errors with substrings like `device:\\\"eth0\\\"` mentioned in a comment in [2692](https://github.com/kata-containers/runtime/issues/2692#issuecomment-634170574).

Currently the only way I see to solve this is preprocessing strings with with substrings known to cause errors, but it's not ideal...
