### ISSUE TITLE
ci/install_runtime: Need a way to skip docker configuration

### ISSUE THREAD

**Issue by wainersm** [kata-containers/tests#2600]
Currently [install_runtime.sh](https://github.com/kata-containers/tests/blob/master/.ci/install_runtime.sh) configures kata as a runtime for docker if `TEST_CGROUPSV2==false`. I am looking for way to skip this configuration even though `TEST_CGROUPSV2==false`. The context is in #2527 , where I need to install kata in a well-known path inside a container image, and I don't need to get docker configured (docker isn't installed in the built container at all).

Initially I thought in change the script to include an extra condition (`TEST_DOCKER==true`). Like:
```
diff --git a/.ci/install_runtime.sh b/.ci/install_runtime.sh
index 7e29883..3bb2a52 100755
--- a/.ci/install_runtime.sh
+++ b/.ci/install_runtime.sh
@@ -110,7 +110,7 @@ if [ "$USE_VSOCK" == "yes" ]; then
        fi
 fi
 
-if [ "${TEST_CGROUPSV2}" == "false" ]; then
+if [ "${TEST_CGROUPSV2}" == "false" ] && [ "${TEST_DOCKER}" == "true" ]; then
        case "${KATA_HYPERVISOR}" in
                "cloud-hypervisor" | "qemu" | "firecracker")
                        echo "Add kata-runtime as a new Docker runtime."

```
However this solution seems wrong because there is the containerd-cri tests which needs to have docker configured too (I suppose on context of containerd-cri tests `TEST_DOCKER` is set to `false`).

So could you advise me how can I possible solve this puzzle?

**Comment by wainersm** [comment]
@jodh-intel @chavafg mind to help me where too?

**Comment by chavafg** [comment]
Hi @wainersm, 

Sorry for not answering before. 

yes, you are right, using `TEST_DOCKER` variable won't help, as this variable is only used to decide if the CI will be running docker integration tests or not, but we will still be running other tests like netmon, stability which are not part of the docker integration, but use docker+kata runtime.

One option I see here is to create a new flag (e.g. `OPENSHIFT_CI="${OPENSHIFT_CI:-false}"`) for your use case which you'll be able to use over other scripts, something like:
```
if [ "$OPENSHIFT_CI" == false ]; then
   echo "Add kata-runtime as a new Docker runtime."
   ...
fi
```

BTW, I am not sure why we're including a `case` for the hypervisors here. I think this was done before because firecracker configuration was done somewhere else, but now it is not the case. I think that part can be removed.
/cc @GabyCT @jcvenegas who may also give input.

**Comment by wainersm** [comment]
> Hi @wainersm,
> 
> Sorry for not answering before.

Actually you guys are very responsive, thanks!

> yes, you are right, using `TEST_DOCKER` variable won't help, as this variable is only used to decide if the CI will be running docker integration tests or not, but we will still be running other tests like netmon, stability which are not part of the docker integration, but use docker+kata runtime.
> 
> One option I see here is to create a new flag (e.g. `OPENSHIFT_CI="${OPENSHIFT_CI:-false}"`) for your use case which you'll be able to use over other scripts, something like:
> 
> ```
> if [ "$OPENSHIFT_CI" == false ]; then
>    echo "Add kata-runtime as a new Docker runtime."
>    ...
> fi
> ```
> 

Introducing this new ```OPENSHIFT_CI``` would be very handy in the other scripts that I've been adapting for the openshift-ci case too. For example, in #2596 I added a new `RUN_KATA_CHECK` that would be not needed If I could simply have a guard using `OPENSHIFT_CI==false`.

> BTW, I am not sure why we're including a `case` for the hypervisors here. I think this was done before because firecracker configuration was done somewhere else, but now it is not the case. I think that part can be removed.
> /cc @GabyCT @jcvenegas who may also give input.

I can remove it in this PR if not needed anymore.
