### ISSUE TITLE
2.0: ARM CI is trying to download non-existing cri-containerd binary

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/tests#2743]
It is NOT network issue. /cc @Pennyzct

Ref: http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-ARM-PR/97/console

```
Download tarball from https://storage.googleapis.com/cri-containerd-release/cri-containerd-3a4acfbc99aa976849f51a8edd4af20ead51d8d7.linux-arm64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 
```

**Comment by GabyCT** [comment]
@jongwu here it is the ARM issue

**Comment by Pennyzct** [comment]
Hi @bergwolf 
It is a predicted error in installing containerd-cri. Since upstream, for now, only provides release binaries for `x86_64`, we will fail on downloading tarballs for `aarch64`. 
So in current installing script, when we failed on downloading binaries, we will try to build from source code. ;) 

@jongwu should be fixing recent CI turbulence on https://github.com/kata-containers/tests/pull/2759

**Comment by bergwolf** [comment]
#2759 is merged. Let's close it. Thanks @Pennyzct @jongwu !
