### ISSUE TITLE
CLH CI regression for kata 2.0 in the kata-containers repo (2.0-dev branch) 

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/tests#2858]
We observe regressions on the CLH CI for kata 2.0 with our `kata-container `repo: http://jenkins.katacontainers.io/job/jobs-2.0/job/kata-2-ubuntu-1804-PR-cloud-hypeprvisor-k8s-containerd/.  Based on the [latest failure from run 139](http://jenkins.katacontainers.io/job/jobs-2.0/job/kata-2-ubuntu-1804-PR-cloud-hypeprvisor-k8s-containerd/139/console), it is likely to be a CI setup issue.

Looks like it is cloning `github.com/kata-containers/agent` and then trying to checkout `2.0-dev` branch from there. It is clearly wrong as we only have `2.0-dev` in `github.com/kata-containers/kata-containers` repository.

```
04:11:20 /tmp/jenkins/workspace/jobs-2.0/kata-2-ubuntu-1804-PR-cloud-hypeprvisor-k8s-containerd/go/src/github.com/kata-containers/kata-containers
04:11:20 Cloning github.com/kata-containers/agent
04:11:22 /tmp/jenkins/workspace/jobs-2.0/kata-2-ubuntu-1804-PR-cloud-hypeprvisor-k8s-containerd/go/src/github.com/kata-containers/agent /tmp/jenkins/workspace/jobs-2.0/kata-2-ubuntu-1804-PR-cloud-hypeprvisor-k8s-containerd/go/src/github.com/kata-containers/kata-containers
04:11:22 Checking out to 2.0-dev
04:11:22 error: pathspec '2.0-dev' did not match any file(s) known to git.
04:11:22 Build step 'Execute shell' marked build as failure
```

**Comment by likebreath** [comment]
@bergwolf Thanks for reporting this issue. We have CLH CI regressions for kata 2.0 on both the `tests` and `kata-containers` repo. I think you are referring to the failure from the CI for the `kata-conatiners` repo, so I updated the issue with a bit more details. I also opened another issue to track the failure on the test repo. Any questions or comments, please let me know. Thanks a lot.

**Comment by likebreath** [comment]
On top of the fix for the CLH CI to the tests repo (https://github.com/kata-containers/tests/pull/2862), the Jenkins config file is also updated with new `Execute shell` script for the CLH CI in the kata-containers repo (http://jenkins.katacontainers.io/job/jobs-2.0/job/kata-2-ubuntu-1804-PR-cloud-hypeprvisor-k8s-containerd/configure). Those two changes together should fix the regression, but we will need to confirm after landing #2862.

For a record, I pasted below the `Execute shell` script we are using. It is borrowed from the [`kata-2.0-ubuntu` CI config](http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-PR/configure),  with a different `CI_JOB` env variable (`CLOUD-HYPERVISOR-K8S-CONTAINERD` vs `CRI_CONTAINERD_K8S`).


```
#!/bin/bash

set -e

export ghprbPullId
export ghprbTargetBranch
export DEBUG=true
export CI="true"
export CI_JOB="CLOUD-HYPERVISOR-K8S-CONTAINERD"
export SHIMV2_TEST="true"

export GOPATH=${WORKSPACE}/go
export PATH=${GOPATH}/bin:/usr/local/go/bin:/usr/sbin:${PATH}
export GOROOT="/usr/local/go"

# TEST
kata_repo="github.com/kata-containers/kata-containers"
kata_repo_dir="${GOPATH}/src/${kata_repo}"
mkdir -p "${kata_repo_dir}"

git clone "https://${kata_repo}.git" "${kata_repo_dir}"
cd "${kata_repo_dir}"
# Checkout to 2.0-dev
git checkout "$ghprbTargetBranch"
# END TEST

tests_repo="github.com/kata-containers/tests"
tests_repo_dir="${GOPATH}/src/${tests_repo}"
mkdir -p "${tests_repo_dir}"

git clone "https://${tests_repo}.git" "${tests_repo_dir}"
cd "${tests_repo_dir}"
# Checkout to Target Branch, which should be 2.0-dev
git checkout "$ghprbTargetBranch"
.ci/jenkins_job_build.sh "github.com/kata-containers/kata-containers"
```

/cc  @jcvenegas @GabyCT  @chavafg @amshinde
