### ISSUE TITLE
Decide on ci job(s) for tracing tests

### ISSUE THREAD

**Issue by cmaf** [kata-containers/tests#3990]
Currently, `tracing-test.sh`, which tests runtime tracing, runs in the `CRI_CONTAINERD_K8S_MINIMAL` job. `CRI_CONTAINERD_K8S_MINIMAL` was originally chosen to run `tracing-test.sh` because there was no previous job running it, it did not add a significant amount of time to the job, and there were no other tracing-related tests to group it with at the time (https://github.com/kata-containers/tests/pull/3038/commits/10e30383c434cd358e6e057fa27b4ef5b8408c8f). The test was not given its own job because it is short and it does not make sense to provision & configure resources for a single test. 

There is no reason `tracing-test.sh` and `test-agent-shutdown.sh` need to stay in this particular job. Right now, `test-agent-shutdown.sh` is disabled for `CRI_CONTAINERD_K8S_MINIMAL` and fails on other jobs (see https://github.com/kata-containers/tests/issues/3981), but once fixed we should decide if we want to keep the tests here or move them.

I also have plans to expand the tracing test for CLH. Should we add this test (and possibly other hypervisors) to existing jobs?

Any thoughts? @jodh-intel @chavafg @Jakob-Naucke @jcvenegas @GabyCT

**Comment by Jakob-Naucke** [comment]
I think we have several (partially contrary) ideals for the CI. 
1. None of the jobs should take too long.
2. Collectively, the jobs should cover as much as possible.
3. The jobs should have names that are both short and make it clear what a job consists of. 

To satisfy (2), the tracing tests should run on each configuration that might have (individually) broken tracing. I'm not an expert on what bits tracing touches, but hypervisors seem relevant to me (what about architectures which often only run one suite, guest distros, containerd vs. CRI-O, initrd vs. image?).
To satisfy (1), it may seem like a good idea to manually "load-balance" different tests across jobs like you alluded to. However, this can lead to confusion in (3), because if I read `K8S_MINIMAL`, I wouldn't think it does more than "basic" k8s tests? We could push this further and put more of the non-k8s tests (stability, containerd, vcpus, sandbox_cgroup_only, pmem, ksm) across jobs, but that undermines the name and especially what I think is the purpose of minimal tests. It also makes it harder to cover everything when there's not enough resources to run many jobs -- like on non-x86 architectures.
Therefore, I don't think it really belongs in `MINIMAL`, but it belongs in every potentially affected job. Even if `CRI_CONTAINERD_K8S` takes a little longer yet.

**Comment by Jakob-Naucke** [comment]
@GabyCT I gave a thumbs up on your comment pre-edit :) I think we _should_ run these tests on `CRI_CONTAINERD_K8S` because it is a simple way to run these tests on single-job architectures.

**Comment by cmaf** [comment]
Closing in favor of https://github.com/kata-containers/tests/issues/4195
