### ISSUE TITLE
CI URL checker should only check files changed in a PR

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/tests#409]
The CI URL checker added in #398 checks all URLs in all docs in a repo upon PR submission. This might be a little heavy handed, as a URL going 'dead' in a file untouched in the submitted PR will now block the PR.

One suggestion is that in PRs we only check the files changed by the PR, but in master branch merges we could check all files, which would give us an early heads up on breakages across the repos.

**Comment by jodh-intel** [comment]
And we've just hit an interesting scenario - although the checker should only check files modified by the PR, it can't check those files if the file is newly added... because although the URL *will be valid once merged*, it doesn't yet exist in the repo:

- https://github.com/kata-containers/documentation/pull/153

Hence, we'll need some logic that says, *"if the file is a markdown doc and is newly-added, don't use `curl`, construct what we think the URL should be and compare it to what was found in the doc"*.

**Comment by grahamwhaley** [comment]
Yep, this is sort of what I was saying the other day - if a PR adds a file that is the destination of a URL, the only way you could check that really is correct afaik is to munge the URL to point at the PR branch/path on github and check that, which could be a little tricky.

**Comment by jodh-intel** [comment]
Well either that or just constructing the URL that *will* exist when the PR lands and comparing that to what the doc says. Or maybe we could do both.

Whatever, we need to check these URLs somehow as we have already been impacted by incorrect/dead URLs.

**Comment by jodh-intel** [comment]
Looks like nobody else is going to pick this up, so I'll take it...
