### ISSUE TITLE
ARM and s390x test cases use an older rustc version

### ISSUE THREAD

**Issue by dgibson** [kata-containers/tests#4179]
# Description of problem

The ARM and s390x CI tests use Rust 1.47.0, whereas the bulk of the tests use Rust 1.54.0.  Obviously the current Rust code works with the older version, but it prevents us using some useful features that have been introduced more recently.  For example the in proress PR https://github.com/kata-containers/kata-containers/pull/2927 uses features from Rust 1.52.0 (`str::split_once`) and Rust 1.53.0 (`IntoIterator` implementation for arrays).

The patch could be rewritten to avoid the newer features, but since we already have a newer Rust on x86 it seems more sensible to just update the version on ARM and s390x to match.

# Expected result

All CI tests use the same Rust version.

# Actual result

ARM and s390x have older Rust versions than x86.

**Comment by dgibson** [comment]
To expand on this: for x86, we appear to take the Rust version from `languages.rust.meta.newest-version` in the `versions.yaml` file of the kata-containers repository, in the `.ci/install_rust.sh` script.  But for some reason, the ARM and s390x environments must not use the same script and somehow end up with a different version.

**Comment by Jakob-Naucke** [comment]
There are a bunch of scripts in which we run `{kata-containers/,tests/.}ci/install_rust.sh`.

1. `kata-containers/tools/osbuilder/rootfs-builder/rootfs.sh` for building the guest if Rust is not installed. (Most of the time, this is run in a container which has Rust installed through some custom logic in `osbuilder/scripts/lib.sh`, which is also a bit redundant. Probably a separate issue.) 
2. `kata-containers/.github/workflows/static-checks.yaml` which generally runs on freshly provisioned GHA instances.
3. `tests/.ci/jenkins_job_build.sh` for running static checks on non-x86 (whose CI instances are generally not freshly provisioned) **if Rust is not installed**. (This is why those are on 1.47, that's the version that got installed at some point in the past).
4. `tests/tracing/test-agent-shutdown.sh` if Rust is not installed, which is required for x86 Jenkins CI, since Rust would only be installed in a container from (1).

Also, we have `languages.rust.version`, which I thought we enforced as a minimum, so you could just increment that. _This is no longer the case, we only_ used _to do that in osbuilder._ We could decide to not maintain this (and remove that), or introduce checking logic. Again, probably a separate issue.

I listed all those because we should be careful not to screw up a developer's setup, which has some implications on when we can just blindly install `newest-version`.
Doing that is probably fine for (2) (well, we don't even check there, why would we), but I wouldn't do it (and because of the container build, it isn't really required) for (1), since it's only used for non-container builds, i.e. there's a good chance it is a development setup. Probably also not for (4), even though it is in the `tests` repository.
For this issue, we're mostly looking at (3), where it might be okay to assert no user expectation that their Rust installation would remain unchanged (it's called Jenkins after all, and requires Jenkins-specific environment variables). WDYT?

One might also consider removing Rust after running the job, but that would incur more downloads than we'd need.

Sorry for the brain dump.

**Comment by dgibson** [comment]
I saw `languages.rust.version`, and the comment saying it was the mininum version.  But I didn't actually see something reading that variable, so I wasn't confident that bumping that alone would have an effect.

> For this issue, we're mostly looking at (3), where it might be okay to assert no user expectation that their Rust installation would remain unchanged (it's called Jenkins after all, and requires Jenkins-specific environment variables). WDYT?

I would agree with that assertion.  I also think it's nuts that have essentially *any* persistent state on the CI host, we should be setting it up clean on every run, or things are just ridiculously confusing.  Implementing that without masses of downloads is, I'll grant, trickier.  Then again, this is a containers project, and AFAICT the entire containers ecosystem is pretty much predicated on downloading all the things, all the time (which, as someone ~200ms latency away from docker.io, is pretty dang irritating).

**Comment by Jakob-Naucke** [comment]
> I also think it's nuts that have essentially _any_ persistent state on the CI host, we should be setting it up clean on every run, or things are just ridiculously confusing. Implementing that without masses of downloads is, I'll grant, trickier. Then again, this is a containers project, and AFAICT the entire containers ecosystem is pretty much predicated on downloading all the things, all the time (...).

In that case, we should enhance `gen_clean_arch` in `tests/.ci/lib.sh` to remove Rust. I guess the impact is not huge when many of our tests already run on freshly provisioned instances anyhow.

**Comment by dgibson** [comment]
> > I also think it's nuts that have essentially _any_ persistent state on the CI host, we should be setting it up clean on every run, or things are just ridiculously confusing. Implementing that without masses of downloads is, I'll grant, trickier. Then again, this is a containers project, and AFAICT the entire containers ecosystem is pretty much predicated on downloading all the things, all the time (...).
> 
> In that case, we should enhance `gen_clean_arch` in `tests/.ci/lib.sh` to remove Rust. I guess the impact is not huge when many of our tests already run on freshly provisioned instances anyhow.

Sorry, I should clarify.  We should be enforcing a clean, consistent test environment from *outside*, that is, in a way that doesn't rely on the test scripts cleaning up after themselves.  modifying `gen_clean_arch` doesn't accomplish that.  I'm also ok with persistence, as long as it is managed *outside* the scope of the test scripts themselves.  The thing I think is totally broken is that one test run can affect the next one by messing up the environment.

**Comment by Jakob-Naucke** [comment]
hit us in https://github.com/kata-containers/kata-containers/pull/3253
