### ISSUE TITLE
ci: URL check fails on non x86 baseline jobs

### ISSUE THREAD

**Issue by Amulyam24** [kata-containers/tests#4408]
```
06:15:06 ERROR: Invalid URL 'https://github.com/kata-containers/tests/blob/main/README.md#breaking-compatibility' found in the following files:
06:15:06 
06:15:06 tools/packaging/kernel/README.md
06:15:06 ERROR: Invalid URL 'https://github.com/kata-containers/tests/tree/main/.ci' found in the following files:
06:15:06 
06:15:06 docs/Documentation-Requirements.md
06:15:06 tools/packaging/kernel/README.md
06:15:06 ERROR: Invalid URL 'https://github.com/kata-containers/tests/tree/main/.ci/kata-doc-to-script.sh' found in the following files:
06:15:06 
06:15:06 docs/Documentation-Requirements.md
06:15:06 ERROR: Invalid URL 'https://github.com/kata-containers/tests/tree/main/cmd/check-spelling' found in the following files:
06:15:06 
06:15:06 docs/code-pr-advice.md
06:15:06 docs/Documentation-Requirements.md
06:15:06 ERROR: Invalid URL 'https://github.com/kata-containers/tests/tree/main/cmd/check-markdown' found in the following files:
06:15:06 
06:15:06 docs/code-pr-advice.md
```
There's a PR raised for the ones returning 429 by @jongwu.
However, I'm not sure on what's causing the invalid URL error. Any thoughts?
cc @Jakob-Naucke

**Comment by Jakob-Naucke** [comment]
This issue has been identified under #4369. The required fixes are in #4370 and https://github.com/kata-containers/kata-containers/pull/3543. I have merged the former PR on **stable** and, to this day, have not forward ported because we weren't seeing these issues on PR jobs on main (note that you might see different results on full CI runs, which differ from our PR runs a little) _and_ because I have a question [here](https://github.com/kata-containers/tests/pull/4385#issuecomment-1019991100) whose answer might introduce some more merge mess. **However**, since you're affected, let me just make the forward port.

**Comment by jongwu** [comment]
thanks @Jakob-Naucke -, hope it works.

**Comment by Jakob-Naucke** [comment]
forward port is #4409

**Comment by GabyCT** [comment]
Closing this issue as it was solved
