### ISSUE TITLE
CC: multi-arch support for quay.io/kata-containers/confidential-containers

### ISSUE THREAD

**Issue by BbolroC** [kata-containers/tests#5258]
**Which feature do you think can be improved?**

During an e2e test for `cc-kubernetes` on s390x to fix #5256 (see the [log](http://jenkins.katacontainers.io/job/kata-containers-CCv0-tests-ubuntu-20.04-s390x-PR/169/consoleText) on Jenkins CI), the following tests failed due to lack of the test image ([quay.io/kata-containers/confidential-containers:signed](https://quay.io/repository/kata-containers/confidential-containers?tab=tags)) for s390x:

```
not ok 3  Test can pull an unencrypted image inside the guest
not ok 4  Test can pull a unencrypted signed image from a protected registry
```

We could make the image (and other tags, for example, `[other_signed|unsigned|cosign-signed|cosign-signed-key2]`) multi-arch compatible via `qemu-user-static`.

**How can it be improved?**

Basic instructions for how to build a multi-arch image with a single tag is explained at https://github.com/kata-containers/kata-containers/issues/5660. We could make a build step automatic via a task in one of the GitHub action workflows (or dedicated).

I look forward to hear any thoughts from @stevenhorsman and @Xynnn007.

cc: @hbrueckner

**Comment by stevenhorsman** [comment]
So, there might be better ways, but the rough instructions to the process I took to create the images is:
- Install the required pre-reqs: `skopeo` and a gpg package (I used `gnupg2`), but I think others are available
- Generate a GPG key pair with `gpg2 --gen-key`. At the prompt enter your name, email, 'O' and a passphrase, then wave your mouse around to generate some entropy, if required
- Set your Quay credentials in a env var: `export QUAY_CREDS="<red hat username>:<quay encrypted password>"`
- Push the properly signed image `http://quay.io/kata-containers/confidential-containers:signed` with: 
```
skopeo copy --insecure-policy "docker://docker.io/library/busybox:latest" "docker://quay.io/kata-containers/confidential-containers:signed" --sign-by "<your email from the gpg creation>" --dest-creds=${QUAY_CREDS}
```
- Push the unsigned image with:
```
skopeo copy --insecure-policy "docker://docker.io/library/busybox:latest" "docker://quay.io/kata-containers/confidential-containers:unsigned" --dest-creds=${QUAY_CREDS}
```
- To create the `quay.io/kata-containers/confidential-containers:other_signed` image I use a different VM with a new GPG key and used the nginx image for a different digest:
```
skopeo copy --insecure-policy "docker://docker.io/library/nginx:latest" "docker://quay.io/kata-containers/confidential-containers:signed" --sign-by "<your email from the gpg creation>" --dest-creds=${QUAY_CREDS}
```
I then had to upload my public GPG key and the signatures I created as part of the integration tests. They have since spread into a few different places now as well, but here are the ones I know of for kata-conatiners:
- https://github.com/kata-containers/tests/blob/CCv0/integration/confidential/fixtures/offline-fs-kbc/aa-offline_fs_kbc-resources.json 
- https://github.com/kata-containers/tests/tree/CCv0/integration/confidential/fixtures/quay_verification

And for image-rs and the attestation-agent:
- https://github.com/confidential-containers/image-rs/blob/main/test_data/offline-fs-kbc/aa-offline_fs_kbc-resources.json 
- https://github.com/confidential-containers/image-rs/tree/main/test_data/simple-signing-scheme
- https://github.com/confidential-containers/attestation-agent/blob/main/src/kbc_modules/offline_fs_kbc/aa-offline_fs_kbc-resources.json

I don't know if you want to add s390x test support to those other repos, but if you push over the existing image that will need changing, so I'd probably recommend pushing to a different image tag to make this process easier.

I hope this helps.

**Comment by Xynnn007** [comment]
Hi @BbolroC , the steps to sign an image with cosign is here https://github.com/Xynnn007/documentation/blob/main/quickstart.md#signing-the-encryptedunencrypted-image-and-enable-signature-verification-when-running-the-workload

Hope to help!

**Comment by BbolroC** [comment]
@Xynnn007 I have the following questions after successfully uploading the `quay.io/kata-containers/confidential-containers:cosign-signed-s390x`:

1. What is the difference between the tag `cosign-signed` and `cosign-signed-key2`?
2. Is https://github.com/kata-containers/tests/blob/CCv0/integration/confidential/fixtures/cosign/offline-fs-kbc/aa-offline_fs_kbc-resources.json a only place to put a public key to get the test running?

**Comment by Xynnn007** [comment]
Hi @BbolroC 
> * What is the difference between the tag `cosign-signed` and `cosign-signed-key2`?

Sorry for the misleading name. The `cosign-signed-key2` is signed by a different private key from `cosign-signed`, and this case is used in a unit test to ensure that wrong public key cannot pass the signature verification.
 
> * Is https://github.com/kata-containers/tests/blob/CCv0/integration/confidential/fixtures/cosign/offline-fs-kbc/aa-offline_fs_kbc-resources.json a only place to put a public key to get the test running?

I'm not sure how `kata-containers/test` runs. However, for offline-fs-kbc, the `offline_fs_kbc-resources.json` is the only thing needed to put the public key. Except for public key, `policy.json` inside `offline_fs_kbc-resources.json` should also be configured that image `quay.io/kata-containers/confidential-containers:cosign-signed-s390x` follow `sigstoreBy` requirement.

**Comment by BbolroC** [comment]
@Xynnn007 Thanks for the detailed explanation. This helps a lot!
