### ISSUE TITLE
CI: fix flannel 0.20 not working with ppc64le job

### ISSUE THREAD

**Issue by wainersm** [kata-containers/tests#5403]
On pull request https://github.com/kata-containers/tests/pull/5334 it was updated the version of flannel used on the k8s tests because the old version became dysfunctional, thus many CI jobs were failing. The bump in flannel version indeed fixed the problem on all affected jobs except for the ppc64le one.

@Amulyam24 made a preliminary assessment  (see https://github.com/kata-containers/tests/pull/5334#issuecomment-1399413414) and it seems the flannel 0.20 image has no build for ppc64le.

The ppc64le job is broken and so must be fixed.

Cc @Amulyam24 @GabyCT @ryansavino @cmaf @fidencio

**Comment by Amulyam24** [comment]
Hi @ryansavino, regarding this - [#5334(comment)](https://github.com/kata-containers/tests/pull/5334#issuecomment-1400653150) 

The image `docker.io/flannel/flannel-cni-plugin:v1.1.2` does have support for `ppc64le`. Will be good to check with them on their next release and in the mean time I can create a fix to use latest instead of v0.20.

**Comment by ryansavino** [comment]
@Amulyam24 looks like flannel just release 0.21.0 and it has the working image:
https://github.com/flannel-io/flannel/blob/v0.21.0/Documentation/kube-flannel.yml

**Comment by Amulyam24** [comment]
Thanks @ryansavino. Updated the PR.
