### ISSUE TITLE
CI failure: missing /usr/share/kata-containers/kata-containers.img

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/tests#548]
Saw with http://jenkins.katacontainers.io/job/kata-containers-runtime-fedora-27-PR/314/console

```
/usr/share/defaults/kata-containers/configuration.toml: file /usr/share/kata-containers/kata-containers.img does not exist
Build step 'Execute shell' marked build as failure
Performing Post build task...
Match found for :.* : True
Logical operation result is TRUE
Running script  : #!/bin/bash
```

**Comment by jodh-intel** [comment]
It's rather difficult picking over that log and correlating it to all the CI scripts, but I *think* what happened is:

- the CI tried to install the packaged image from OBS, but it failed due to network issues:
  ```
  Failed to synchronize cache for repo 'home_katacontainers_release', disabling.
  Error: Unable to find a match
  Last metadata expiration check: 0:01:10 ago on Tue 31 Jul 2018 04:01:41 AM UTC.
  No match for argument: kata-containers-image
  ```
- the CI then tried to build an image with osbuilder, but that also failed due to network issues:
  ```
  Error: Error downloading packages:
  Status code: 503 for https://mirrors.fedoraproject.org/metalink?repo=fedora-28&arch=x86_64
  The command '/bin/sh -c dnf install -y qemu-img parted gdisk e2fsprogs' returned a non-zero code: 1
  install: cannot stat 'kata-containers.img': No such file or directory
  ```

Conclusion: networks suck :smile:

**Comment by bergwolf** [comment]
hah, I have a feeling that fedora CI is more prone to network issues. ^_^

Anyway, closing this since it is not our fault. Thanks for checking @jodh-intel !
