### ISSUE TITLE
Add docker static binaries in manage_ctr_mgr.sh

### ISSUE THREAD

**Issue by alicefr** [kata-containers/tests#910]
Docker doesn't deliver the docker package for all the distributions and architectures. [Here](https://docs.docker.com/install/#supported-platforms) an overview of the supported distros and architectures. However, they also build [static binaries](https://download.docker.com/linux/static/stable/). It could be useful to install the docker static binaries in the case the package is not available. In this way, it is also possible to use a recent docker version. The systemd service files in [moby](https://github.com/moby/moby/tree/master/contrib/init/systemd) could be use to enable the docker service. For example, that could enable the testsuite to be tested for s390x on fedora.

**Comment by jodh-intel** [comment]
Hi @alicefr - do you know why Docker is only available for Ubuntu on s390? I guess static binaries could work for the CI specifically, but would not be appropriate for user installs since, not using distro packaging, they would not be automatically updated.

On a related note, I do wonder if we should try to combine `manage_ctr_mgr.sh` (CI) and [`kata-manager.sh`](
https://github.com/kata-containers/tests/tree/master/cmd/kata-manager) (used by users) somehow.

@chavafg - wdyt?

**Comment by alicefr** [comment]
@jodh-intel you're right the static binaries won't be updated. I don't know why they don't deliver for other distro. I'll ask. The docker version provided by fedora is also pretty old: `1.13.1`
